[package]
name = "rolling-stats"
version = "0.1.0"
edition = "2021"

# [lib]
# crate-type = ["staticlib"]

[profile.dev]
panic="abort"

[profile.release]
panic = "abort"

[dependencies]
byteorder = "1.5.0"
heapless = "0.8.0"
rand = "0.8.5"
rand_distr = "0.4.3"
libc-print = "0.1.23"
